In [1]:
paragraph = '''Karate (空手) Japanese pronunciation: [kaɾate]; Okinawan pronunciation: [kaɾati]), also karate-do (空手道, Karate-dō), is a martial art developed in the Ryukyu Kingdom. 
It developed from the indigenous Ryukyuan martial arts (called te (手), "hand"; tī in Okinawan) under the influence of Chinese martial arts.
While modern karate is primarily a striking art that uses punches and kicks, traditional karate training also employs throwing and joint locking techniques.
A karate practitioner is called a karate-ka (空手家). Beginning in the 1300s, early Chinese martial artists brought their techniques to Okinawa.
Despite the Ryukyu Kingdom being turned into a puppet state by Japanese samurai in 1609, after the Invasion of Ryukyu, its cultural ties to China remained strong.
Since Ryukyuans were banned from carrying swords under samurai rule, groups of young aristocrats created unarmed combat methods as a form of resistance, combining Chinese and local styles of martial arts.
Training emphasized self-discipline. This blend of martial arts became known as kara-te 唐手, which translates to "Chinese hand."
Initially, there were no uniforms, colored belts, ranking systems, or standardized styles.
Many elements essential to modern karate were actually incorporated a century ago.'''
print(paragraph)

Karate (空手) Japanese pronunciation: [kaɾate]; Okinawan pronunciation: [kaɾati]), also karate-do (空手道, Karate-dō), is a martial art developed in the Ryukyu Kingdom. 
It developed from the indigenous Ryukyuan martial arts (called te (手), "hand"; tī in Okinawan) under the influence of Chinese martial arts.
While modern karate is primarily a striking art that uses punches and kicks, traditional karate training also employs throwing and joint locking techniques.
A karate practitioner is called a karate-ka (空手家). Beginning in the 1300s, early Chinese martial artists brought their techniques to Okinawa.
Despite the Ryukyu Kingdom being turned into a puppet state by Japanese samurai in 1609, after the Invasion of Ryukyu, its cultural ties to China remained strong.
Since Ryukyuans were banned from carrying swords under samurai rule, groups of young aristocrats created unarmed combat methods as a form of resistance, combining Chinese and local styles of martial arts.
Training emphasized self-dis

In [2]:
import nltk
from nltk.tokenize import sent_tokenize

In [3]:
sentences = sent_tokenize(paragraph)
print(sentences)

['Karate (空手) Japanese pronunciation: [kaɾate]; Okinawan pronunciation: [kaɾati]), also karate-do (空手道, Karate-dō), is a martial art developed in the Ryukyu Kingdom.', 'It developed from the indigenous Ryukyuan martial arts (called te (手), "hand"; tī in Okinawan) under the influence of Chinese martial arts.', 'While modern karate is primarily a striking art that uses punches and kicks, traditional karate training also employs throwing and joint locking techniques.', 'A karate practitioner is called a karate-ka (空手家).', 'Beginning in the 1300s, early Chinese martial artists brought their techniques to Okinawa.', 'Despite the Ryukyu Kingdom being turned into a puppet state by Japanese samurai in 1609, after the Invasion of Ryukyu, its cultural ties to China remained strong.', 'Since Ryukyuans were banned from carrying swords under samurai rule, groups of young aristocrats created unarmed combat methods as a form of resistance, combining Chinese and local styles of martial arts.', 'Traini

In [4]:
import re
newSents = []

for sent in sentences:
    sent = re.sub(r"[^\w\s]", "", sent.lower())
    newSents.append(sent)
print(newSents)


['karate 空手 japanese pronunciation kaɾate okinawan pronunciation kaɾati also karatedo 空手道 karatedō is a martial art developed in the ryukyu kingdom', 'it developed from the indigenous ryukyuan martial arts called te 手 hand tī in okinawan under the influence of chinese martial arts', 'while modern karate is primarily a striking art that uses punches and kicks traditional karate training also employs throwing and joint locking techniques', 'a karate practitioner is called a karateka 空手家', 'beginning in the 1300s early chinese martial artists brought their techniques to okinawa', 'despite the ryukyu kingdom being turned into a puppet state by japanese samurai in 1609 after the invasion of ryukyu its cultural ties to china remained strong', 'since ryukyuans were banned from carrying swords under samurai rule groups of young aristocrats created unarmed combat methods as a form of resistance combining chinese and local styles of martial arts', 'training emphasized selfdiscipline', 'this blen

In [5]:
from nltk.corpus import stopwords

fillerWords = stopwords.words("english")
processedSents = []

for sent in newSents:
    words = sent.split(" ")
    processedSents.append(words)

print(processedSents)


[['karate', '空手', 'japanese', 'pronunciation', 'kaɾate', 'okinawan', 'pronunciation', 'kaɾati', 'also', 'karatedo', '空手道', 'karatedō', 'is', 'a', 'martial', 'art', 'developed', 'in', 'the', 'ryukyu', 'kingdom'], ['it', 'developed', 'from', 'the', 'indigenous', 'ryukyuan', 'martial', 'arts', 'called', 'te', '手', 'hand', 'tī', 'in', 'okinawan', 'under', 'the', 'influence', 'of', 'chinese', 'martial', 'arts'], ['while', 'modern', 'karate', 'is', 'primarily', 'a', 'striking', 'art', 'that', 'uses', 'punches', 'and', 'kicks', 'traditional', 'karate', 'training', 'also', 'employs', 'throwing', 'and', 'joint', 'locking', 'techniques'], ['a', 'karate', 'practitioner', 'is', 'called', 'a', 'karateka', '空手家'], ['beginning', 'in', 'the', '1300s', 'early', 'chinese', 'martial', 'artists', 'brought', 'their', 'techniques', 'to', 'okinawa'], ['despite', 'the', 'ryukyu', 'kingdom', 'being', 'turned', 'into', 'a', 'puppet', 'state', 'by', 'japanese', 'samurai', 'in', '1609', 'after', 'the', 'invasion'

In [15]:
newProcessedSents = []

for s in processedSents:
    #print(s)
    newSent = []
    for w in s:
        if w not in fillerWords:
            newSent.append(w)
    newProcessedSents.append(newSent)
print(newProcessedSents)

[['karate', '空手', 'japanese', 'pronunciation', 'kaɾate', 'okinawan', 'pronunciation', 'kaɾati', 'also', 'karatedo', '空手道', 'karatedō', 'martial', 'art', 'developed', 'ryukyu', 'kingdom'], ['developed', 'indigenous', 'ryukyuan', 'martial', 'arts', 'called', 'te', '手', 'hand', 'tī', 'okinawan', 'influence', 'chinese', 'martial', 'arts'], ['modern', 'karate', 'primarily', 'striking', 'art', 'uses', 'punches', 'kicks', 'traditional', 'karate', 'training', 'also', 'employs', 'throwing', 'joint', 'locking', 'techniques'], ['karate', 'practitioner', 'called', 'karateka', '空手家'], ['beginning', '1300s', 'early', 'chinese', 'martial', 'artists', 'brought', 'techniques', 'okinawa'], ['despite', 'ryukyu', 'kingdom', 'turned', 'puppet', 'state', 'japanese', 'samurai', '1609', 'invasion', 'ryukyu', 'cultural', 'ties', 'china', 'remained', 'strong'], ['since', 'ryukyuans', 'banned', 'carrying', 'swords', 'samurai', 'rule', 'groups', 'young', 'aristocrats', 'created', 'unarmed', 'combat', 'methods', '

In [17]:
from gensim.models import Word2Vec

embedding = Word2Vec(newProcessedSents, vector_size = 1, min_count = 1, epochs = 100)
print(embedding)

Word2Vec<vocab=99, vector_size=1, alpha=0.025>


In [21]:
embeddingList = []

for s in newProcessedSents:
    vectors = []
    for w in s:
        vectors.append(embedding.wv[w][0])
    embeddingList.append(vectors)
print(embeddingList)

[[0.09566827, -0.16977529, -0.32406095, -0.10572461, 0.8671425, -0.72427666, -0.10572461, -0.512819, 0.45526928, 0.06272787, -0.41959962, -0.8881611, 0.2200935, -0.5975694, -0.38199645, -0.77013266, 0.77633446], [-0.38199645, -0.14236602, 0.5941492, 0.2200935, 1.0471752, -0.07492796, -0.34565708, 0.0852936, -0.3810775, 1.0423832, -0.72427666, -0.7037837, 0.73339564, 0.2200935, 1.0471752], [1.0118916, 0.09566827, 1.0507739, 0.6099847, -0.5975694, -0.76243156, -0.6002585, -0.6003557, 0.014739371, 0.09566827, 0.76445615, 0.45526928, 0.8079705, 0.22331615, 0.8583108, 0.7532485, -0.20758359], [0.09566827, -0.74394774, -0.07492796, -0.37096348, -0.93085575], [-0.008240537, 0.7049991, -0.22389731, 0.73339564, 0.2200935, 0.6132319, 1.0058405, -0.20758359, 0.06819469], [0.52296364, -0.77013266, 0.77633446, 0.20917833, -0.13441205, -0.7246335, -0.32406095, 0.32120582, 0.05572605, 0.45412645, -0.77013266, 0.6946418, 0.838576, -0.40726742, 0.30244154, 0.71467113], [0.03432754, -0.33005735, 0.83958

In [27]:
lengths = []
for s in embeddingList:
    lengths.append(len(s))
    #print(len(s))
maxLength = max(lengths)

In [ ]:
import numpy as np
newEmbeddingList = []

for s in embeddingList:
    newEmbeddingList.append(np.pad(s, (0, maxLength-len(s))))
print(newEmbeddingList)



[array([ 0.09566827, -0.16977529, -0.32406095, -0.10572461,  0.8671425 ,
       -0.72427666, -0.10572461, -0.512819  ,  0.45526928,  0.06272787,
       -0.41959962, -0.8881611 ,  0.2200935 , -0.5975694 , -0.38199645,
       -0.77013266,  0.77633446,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32), array([-0.38199645, -0.14236602,  0.5941492 ,  0.2200935 ,  1.0471752 ,
       -0.07492796, -0.34565708,  0.0852936 , -0.3810775 ,  1.0423832 ,
       -0.72427666, -0.7037837 ,  0.73339564,  0.2200935 ,  1.0471752 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32), array([ 1.0118916 ,  0.09566827,  1.0507739 ,  0.6099847 , -0.5975694 ,
       -0.76243156, -0.6002585 , -0.6003557 ,  0.01473937,  0.09566827,
        0.76445615,  0.45526928,  0.8079705 ,  0.22331615,  0.8583108 ,
        0.7532485 , -0.20758359,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], d

In [33]:
similarity_matrix = np.zeros((len(newEmbeddingList), len(newEmbeddingList)))
print(similarity_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
from scipy import spatial


for s in range(len(newEmbeddingList)):
    for w in range(len(newEmbeddingList)):
        similarity_matrix[s][w] = (1-spatial.distance.cosine(newEmbeddingList[s], newEmbeddingList[w]))
print(similarity_matrix)

[[ 1.          0.22866733 -0.2905803  -0.2254696  -0.10080671 -0.06078912
  -0.01765348 -0.00937968  0.17724995 -0.27503717 -0.1051627 ]
 [ 0.22866733  1.          0.11140335 -0.34364048 -0.07184371  0.34175938
   0.31422052  0.02723964  0.27277458  0.11328774  0.26377922]
 [-0.2905803   0.11140335  1.          0.08334073 -0.18980309  0.53729522
   0.06096351  0.47526658 -0.08400761 -0.31027544  0.50878859]
 [-0.2254696  -0.34364048  0.08334073  1.         -0.49030855  0.21793477
  -0.02708263  0.27098721 -0.50510323  0.20510213 -0.40314373]
 [-0.10080671 -0.07184371 -0.18980309 -0.49030855  1.         -0.39829451
   0.12962019 -0.25401467 -0.01257439 -0.09356204  0.04942506]
 [-0.06078912  0.34175938  0.53729522  0.21793477 -0.39829451  1.
   0.19982307  0.49235845 -0.0057043   0.08834835  0.17021234]
 [-0.01765348  0.31422052  0.06096351 -0.02708263  0.12962019  0.19982307
   1.          0.19308588  0.26733351  0.13656448 -0.09508524]
 [-0.00937968  0.02723964  0.47526658  0.27098721

In [51]:
import networkx

graph = networkx.from_numpy_array(similarity_matrix)
networkx.pagerank(graph, tol = 1000.0)


{0: 0.3235914536010891,
 1: 0.3080028269463886,
 2: 0.01443234557901337,
 3: -0.3352671948262823,
 4: -0.04875936210681672,
 5: 0.09669649417642907,
 6: 0.08390084221753023,
 7: 0.04490595897663452,
 8: 0.32417660189076297,
 9: -0.012129705329372699,
 10: 0.2004497388746236}